### ISSUE TITLE
[BUG] set version 0.7.1 on pubspec.yaml, but pointing to version 0.7.2 on pubspec.lock

### ISSUE THREAD

**Issue by tijanirf** [transistorsoft/flutter_background_fetch#218]
**Your Environment**
* Plugin version: 0.7.1
* Platform: Android
* Flutter info (`flutter info`, `flutter doctor`):
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.2.3 20D91 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3) 
[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.55.2)
* Plugin config

**To Reproduce**
1. add `background_fetch: ^0.7.1` to pubspec.yaml
2. run `flutter clean && flutter pub get`
3. build

**Debug logs**
Getting error and logs as mentioned in [this issue](https://github.com/transistorsoft/flutter_background_fetch/issues/207)

**Expected**
- version pointed to 0.7.1 on `pubspec.lock`
- The app can be built normally. My other project also using version 0.7.1 and it works fine.

**Temporary Solution**
After a while, I tried to check my `pubspec.lock` and it shown:
```
background_fetch:
    dependency: "direct main"
    description:
      name: background_fetch
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.7.2"
```
I can build my app if I manually change the version on `pubspec.lock` to 0.7.1 and run `flutter pub get` again.
Please CMIIW if it's not a bug, but IMHO it could give us a hard time because we tend to overlook the `pubspec.lock`

***edit***
- update expected
